### PR TITLE
Added Line Shop

### PR DESCRIPTION
**Pull request by ervan0707**

### CODE REVIEW

**Comment by frisgajohan** [comment]
great job dude

**Comment by doodspav** [comment]
This is great - hope it gets implemented (along with some of the other shop functions)

**Comment by doodspav** [comment]
@ervan0707 can i suggest also have getActivePurchases(language, country, start=0, size=9999)?
Gets you all the stickers you own (and size is 9999 because i know people that have over 2k stickers).

**Comment by ervan0707** [comment]
@doodspav done

**Comment by fadhiilrachman** [comment]
@ervan0707 Great! Thank you for your contribute

**Pull request merged**
